name: "Install Theos"
description: "Install Theos and prepare it for building projects"
author: "Randomblock1"

inputs:
  theos-sdks:
    description: "URL to clone SDKs"
    required: false
    default: "https://github.com/theos/sdks"

runs:
  using: "composite"
  steps:
    - name: Setup Theos
      shell: bash
      run: |
        export THEOS=~/theos
        git clone --recursive https://github.com/theos/theos.git $THEOS
        curl -LO https://github.com/theos/sdks/archive/master.tar.gz
        tar -xf master.tar.gz -C $THEOS/sdks --strip-components=1
        echo "THEOS=$THEOS" >> $GITHUB_ENV
